version: "3.3"

services:

 #Proverá o PHP para sua aplicação;
  php:

    image: "jarzamendia/cake-php-fpm"

    #ports:
      #- target: 8080
          #published: 8080
          #protocol: tcp
          #mode: ingress

    volumes:
      - type: bind
        source: "./app"
        target: "/var/www/app/webroot/"
       
    deploy:

      mode: replicated
      replicas: 1

      restart_policy:
        condition: any

    networks:
      - appnet
 
 #Porta de entrada da aplicação. Responde os arquivos estaticos.
  nginx:

    image: "nginx"

    ports:

      - target: 80
        published: 80
        protocol: tcp
        mode: host

      - target: 443
        published: 443
        protocol: tcp
        mode: host

    volumes:
      - type: bind
        source: "./app"
        target: "/var/www/app/webroot/"

      - type: bind
        source: "./nginx/nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
        
    deploy:

      mode: replicated
      replicas: 1

      restart_policy:
        condition: any

    networks:
      - appnet

#Banco de dados.
  mysql:

    image: "mariadb"

    volumes:
      - type: bind
        source: "./mysql/my.cnf"
        target: /etc/mysql/my.cnf

    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=111111
    
    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: any

    networks:
      - appnet

  adminer:

    image: "adminer"

    ports:

      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    
    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: any

    networks:
      - appnet

#A rede que os containers utilizarão.
networks:
  appnet:
    driver: overlay